server:
  port: 9080

logging:
  level:
    org.springframework: ERROR
    ru.innopolis.stc31.appeal: DEBUG
  pattern:
    console: "[%-5level] %d{HH:mm:ss.SSS} g:%X{guid} o:%X{oper} [%-26logger{26}:%L]: %m%wEx%n"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appeal
    username: appeal
    password: appeal
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate.ddl-auto: none
  liquibase:
    change-log: 'classpath:db/changelog/db.changelog-master.xml'
  output:
    ansi:
      enabled: DETECT

application:
  api:
    uriPrefix: /api/v1.0

config:
  security:
    secret: "GJDUWE9REC"

cloudinary:
  config:
    cloudName: diq5takuo
    apiKey: 167961632929967
    apiSecret: -SvBXhwTs0kxHgjHvyOWN0-CQMM