alter table users drop constraint users_id_map_role_key;

insert into users
values(2,                         /* id */
            1,                          /* role */
            1,                          /* country */
            1,                          /* city */
            3,                          /* street */
            1,                       /* company */
            1,                          /* status */
            'Administrator',            /* login */
            '41ffbfd17a405e414317462720cfad0c6ca43dd4',            /* password */
            'Иван',                     /* name */
            'Иванов',                   /* surname */
            '1982-04-21',               /* birthday */
            89059647574,                /* phone */
            'ivan_ivanov@mail.ru');     /* email */
insert into users
values(3,                         /* id */
            3,                          /* role */
            3,                          /* country */
            6,                          /* city */
            15,                         /* street */
            1,                       /* company */
            1,                          /* status */
            'Moderator',                /* login */
            '0165ee6c8ca8cbdb0faaa7fa869ccf992b233b0f',                /* password */
            'Николай',                  /* name */
            'Николаев',                 /* surname */
            '1979-03-12',               /* birthday */
            89113582432,                /* phone */
            'nikolay_nik@gmail.com');     /* email */
insert into users
values(4,                         /* id */
            3,                          /* role */
            1,                          /* country */
            2,                          /* city */
            6,                          /* street */
            1,                       /* company */
            1,                          /* status */
            'Redactor',            /* login */
            '8904486a6eb692d11a7b088931f6ffbc7e038772',            /* password */
            'Василий',                     /* name */
            'Васильев',                   /* surname */
            '1976-10-02',               /* birthday */
            89006859657,                /* phone */
            'vas_redact@yandex.ru');     /* email */
insert into users
values(5,                         /* id */
            2,                          /* role */
            1,                          /* country */
            1,                          /* city */
            2,                          /* street */
            1,                       /* company */
            2,                          /* status */
            'Deleted_User',            /* login */
            '2965690f248754ece7c85c7206fbb5118f1b0de7',            /* password */
            'Павел',                     /* name */
            'Павлов',                   /* surname */
            '1991-07-30',               /* birthday */
            89637492288,                /* phone */
            'del_pav@yahoo.com');     /* email */
insert into users
values(6,                         /* id */
            2,                          /* role */
            1,                          /* country */
            3,                          /* city */
            9,                          /* street */
            1,                       /* company */
            0,                          /* status */
            'Reg_User',            /* login */
            '232f658e40e6953751a18fa98f410deb5910bd24',            /* password */
            'Владимир',                     /* name */
            'Владимиров',                   /* surname */
            '1988-07-04',               /* birthday */
            89518473339,                /* phone */
            'reg_vlad@mail.ru');     /* email */
insert into users
values(7,                         /* id */
            2,                          /* role */
            2,                          /* country */
            4,                          /* city */
            10,                          /* street */
            2,                       /* company */
            1,                          /* status */
            'Verified_User',            /* login */
            'db6e42816e4f1e5586a1581f011c2f0908beec78',            /* password */
            'Олег',                     /* name */
            'Олегов',                   /* surname */
            '1989-11-20',               /* birthday */
            89817213581,                /* phone */
            'verif_serj@bk.ru');     /* email */
insert into users
values(8,                         /* id */
            2,                          /* role */
            4,                          /* country */
            7,                          /* city */
            16,                          /* street */
            1,                       /* company */
            0,                          /* status */
            'Test_User',            /* login */
            '68844745189a4ef683a5f0c34c51be328b060d88',            /* password */
            'Сергей',                     /* name */
            'Сергеев',                   /* surname */
            '1993-01-05',               /* birthday */
            89743630204,                /* phone */
            'test_oleg@gmail.com');     /* email */
insert into users
values(9,                         /* id */
            1,                          /* role */
            1,                          /* country */
            1,                          /* city */
            3,                          /* street */
            1,                       /* company */
            2,                          /* status */
            'Deleted_Admin',            /* login */
            '5d418d6efc4e4251d16fe5633754e7ce4fb7f379',            /* password */
            'Валерий',                     /* name */
            'Валерьев',                   /* surname */
            '1977-12-03',               /* birthday */
            89328831099,                /* phone */
            'del_adm@inbox.ru');     /* email */