update users set id_role = null where login = 'appeal';
update users set id_role = null where login = 'Administrator';
update users set id_role = null where login = 'Moderator';
update users set id_role = null where login = 'Redactor';
update users set id_role = null where login = 'Deleted_User';
update users set id_role = null where login = 'Reg_User';
update users set id_role = null where login = 'Verified_User';
update users set id_role = null where login = 'Test_User';
update users set id_role = null where login = 'Deleted_Admin';