update users set id_role = 2 where login = 'appeal';
update users set id_role = 1 where login = 'Administrator';
update users set id_role = 3 where login = 'Moderator';
update users set id_role = 3 where login = 'Redactor';
update users set id_role = 2 where login = 'Deleted_User';
update users set id_role = 2 where login = 'Reg_User';
update users set id_role = 2 where login = 'Verified_User';
update users set id_role = 2 where login = 'Test_User';
update users set id_role = 1 where login = 'Deleted_Admin';